sudo: false
services:
  - mongodb
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs-v2'
  - 'iojs-v3'
  - '4'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - npm install -g bower
  - cd example
  - npm install
  - bower install
  - cd ..
matrix:
  allow_failures:
    - node_js: 'iojs-v3'
    - node_js: '4'
